run:
  tests: true
  sckip-dirs:
    - "docs"

linters-settings:
  funlen:
    lines: 150
    statements: 80

  depguard:
    rules:
      main:
        allow:
          - "github.com/disintegration/imaging"
          - "github.com/google/uuid"
          - "github.com/hashicorp/golang-lru/v2/expirable"
          - "github.com/labstack/echo/v4"
          - "github.com/labstack/echo/v4/middleware"
          - "github.com/labstack/gommon/log"
          - "github.com/spf13/cobra"
          - "github.com/spf13/viper"
          - "github.com/swaggo/echo-swagger"
          - "github.com/stretchr/testify/require"

  revive:
    rules:
      - name: blank-imports
        disabled: true

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace