name: Github Actions

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: ~1.19

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build binary
        run: make build

  tests:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - name: Check out code
        uses: actions/checkout@v3

      - name: Unit tests
        run: make test

  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: ~1.19

      - name: Check out code
        uses: actions/checkout@v3

      - name: Linters
        run: make lint